// Mocks generated by Mockito 5.4.6 from annotations
// in alive_app/test/mocks/mock_generators.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:alive_app/core/errors/failures.dart' as _i10;
import 'package:alive_app/features/auth/data/datasources/auth_remote_datasource.dart'
    as _i7;
import 'package:alive_app/features/auth/data/models/user_model.dart' as _i2;
import 'package:alive_app/features/auth/domain/entities/user_entity.dart'
    as _i9;
import 'package:alive_app/features/auth/domain/repositories/auth_repository.dart'
    as _i4;
import 'package:alive_app/features/auth/domain/usecases/get_current_user_usecase.dart'
    as _i13;
import 'package:alive_app/features/auth/domain/usecases/sign_in_with_google_usecase.dart'
    as _i11;
import 'package:alive_app/features/auth/domain/usecases/sign_out_usecase.dart'
    as _i12;
import 'package:alive_app/features/stream/data/datasources/stream_remote_datasource.dart'
    as _i14;
import 'package:alive_app/features/stream/data/models/category_model.dart'
    as _i15;
import 'package:alive_app/features/stream/data/models/stream_model.dart' as _i5;
import 'package:alive_app/features/stream/domain/entities/category_entity.dart'
    as _i17;
import 'package:alive_app/features/stream/domain/entities/stream_entity.dart'
    as _i16;
import 'package:alive_app/features/stream/domain/repositories/stream_repository.dart'
    as _i6;
import 'package:alive_app/features/stream/domain/usecases/follow_streamer_usecase.dart'
    as _i20;
import 'package:alive_app/features/stream/domain/usecases/get_categories_usecase.dart'
    as _i19;
import 'package:alive_app/features/stream/domain/usecases/get_streams_usecase.dart'
    as _i18;
import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUserModel_0 extends _i1.SmartFake implements _i2.UserModel {
  _FakeUserModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthRepository_2 extends _i1.SmartFake
    implements _i4.AuthRepository {
  _FakeAuthRepository_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamModel_3 extends _i1.SmartFake implements _i5.StreamModel {
  _FakeStreamModel_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamRepository_4 extends _i1.SmartFake
    implements _i6.StreamRepository {
  _FakeStreamRepository_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDataSource extends _i1.Mock
    implements _i7.AuthRemoteDataSource {
  @override
  _i8.Stream<_i2.UserModel?> get authStateChanges =>
      (super.noSuchMethod(
            Invocation.getter(#authStateChanges),
            returnValue: _i8.Stream<_i2.UserModel?>.empty(),
            returnValueForMissingStub: _i8.Stream<_i2.UserModel?>.empty(),
          )
          as _i8.Stream<_i2.UserModel?>);

  @override
  _i8.Future<_i2.UserModel> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i8.Future<_i2.UserModel>.value(
              _FakeUserModel_0(this, Invocation.method(#signInWithGoogle, [])),
            ),
            returnValueForMissingStub: _i8.Future<_i2.UserModel>.value(
              _FakeUserModel_0(this, Invocation.method(#signInWithGoogle, [])),
            ),
          )
          as _i8.Future<_i2.UserModel>);

  @override
  _i8.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i2.UserModel?> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue: _i8.Future<_i2.UserModel?>.value(),
            returnValueForMissingStub: _i8.Future<_i2.UserModel?>.value(),
          )
          as _i8.Future<_i2.UserModel?>);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i4.AuthRepository {
  @override
  _i8.Stream<_i9.UserEntity?> get authStateChanges =>
      (super.noSuchMethod(
            Invocation.getter(#authStateChanges),
            returnValue: _i8.Stream<_i9.UserEntity?>.empty(),
            returnValueForMissingStub: _i8.Stream<_i9.UserEntity?>.empty(),
          )
          as _i8.Stream<_i9.UserEntity?>);

  @override
  _i8.Future<_i3.Either<_i10.Failure, _i9.UserEntity>> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue:
                _i8.Future<_i3.Either<_i10.Failure, _i9.UserEntity>>.value(
                  _FakeEither_1<_i10.Failure, _i9.UserEntity>(
                    this,
                    Invocation.method(#signInWithGoogle, []),
                  ),
                ),
            returnValueForMissingStub:
                _i8.Future<_i3.Either<_i10.Failure, _i9.UserEntity>>.value(
                  _FakeEither_1<_i10.Failure, _i9.UserEntity>(
                    this,
                    Invocation.method(#signInWithGoogle, []),
                  ),
                ),
          )
          as _i8.Future<_i3.Either<_i10.Failure, _i9.UserEntity>>);

  @override
  _i8.Future<_i3.Either<_i10.Failure, void>> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i8.Future<_i3.Either<_i10.Failure, void>>.value(
              _FakeEither_1<_i10.Failure, void>(
                this,
                Invocation.method(#signOut, []),
              ),
            ),
            returnValueForMissingStub:
                _i8.Future<_i3.Either<_i10.Failure, void>>.value(
                  _FakeEither_1<_i10.Failure, void>(
                    this,
                    Invocation.method(#signOut, []),
                  ),
                ),
          )
          as _i8.Future<_i3.Either<_i10.Failure, void>>);

  @override
  _i8.Future<_i3.Either<_i10.Failure, _i9.UserEntity?>> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue:
                _i8.Future<_i3.Either<_i10.Failure, _i9.UserEntity?>>.value(
                  _FakeEither_1<_i10.Failure, _i9.UserEntity?>(
                    this,
                    Invocation.method(#getCurrentUser, []),
                  ),
                ),
            returnValueForMissingStub:
                _i8.Future<_i3.Either<_i10.Failure, _i9.UserEntity?>>.value(
                  _FakeEither_1<_i10.Failure, _i9.UserEntity?>(
                    this,
                    Invocation.method(#getCurrentUser, []),
                  ),
                ),
          )
          as _i8.Future<_i3.Either<_i10.Failure, _i9.UserEntity?>>);
}

/// A class which mocks [SignInWithGoogleUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignInWithGoogleUseCase extends _i1.Mock
    implements _i11.SignInWithGoogleUseCase {
  @override
  _i4.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_2(
              this,
              Invocation.getter(#repository),
            ),
            returnValueForMissingStub: _FakeAuthRepository_2(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i4.AuthRepository);

  @override
  _i8.Future<_i3.Either<_i10.Failure, _i9.UserEntity>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i8.Future<_i3.Either<_i10.Failure, _i9.UserEntity>>.value(
                  _FakeEither_1<_i10.Failure, _i9.UserEntity>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
            returnValueForMissingStub:
                _i8.Future<_i3.Either<_i10.Failure, _i9.UserEntity>>.value(
                  _FakeEither_1<_i10.Failure, _i9.UserEntity>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i8.Future<_i3.Either<_i10.Failure, _i9.UserEntity>>);
}

/// A class which mocks [SignOutUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignOutUseCase extends _i1.Mock implements _i12.SignOutUseCase {
  @override
  _i4.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_2(
              this,
              Invocation.getter(#repository),
            ),
            returnValueForMissingStub: _FakeAuthRepository_2(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i4.AuthRepository);

  @override
  _i8.Future<_i3.Either<_i10.Failure, void>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i8.Future<_i3.Either<_i10.Failure, void>>.value(
              _FakeEither_1<_i10.Failure, void>(
                this,
                Invocation.method(#call, []),
              ),
            ),
            returnValueForMissingStub:
                _i8.Future<_i3.Either<_i10.Failure, void>>.value(
                  _FakeEither_1<_i10.Failure, void>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i8.Future<_i3.Either<_i10.Failure, void>>);
}

/// A class which mocks [GetCurrentUserUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCurrentUserUseCase extends _i1.Mock
    implements _i13.GetCurrentUserUseCase {
  @override
  _i4.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_2(
              this,
              Invocation.getter(#repository),
            ),
            returnValueForMissingStub: _FakeAuthRepository_2(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i4.AuthRepository);

  @override
  _i8.Future<_i3.Either<_i10.Failure, _i9.UserEntity?>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i8.Future<_i3.Either<_i10.Failure, _i9.UserEntity?>>.value(
                  _FakeEither_1<_i10.Failure, _i9.UserEntity?>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
            returnValueForMissingStub:
                _i8.Future<_i3.Either<_i10.Failure, _i9.UserEntity?>>.value(
                  _FakeEither_1<_i10.Failure, _i9.UserEntity?>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i8.Future<_i3.Either<_i10.Failure, _i9.UserEntity?>>);
}

/// A class which mocks [StreamRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockStreamRemoteDataSource extends _i1.Mock
    implements _i14.StreamRemoteDataSource {
  @override
  _i8.Future<List<_i5.StreamModel>> getStreams({String? categoryId}) =>
      (super.noSuchMethod(
            Invocation.method(#getStreams, [], {#categoryId: categoryId}),
            returnValue: _i8.Future<List<_i5.StreamModel>>.value(
              <_i5.StreamModel>[],
            ),
            returnValueForMissingStub: _i8.Future<List<_i5.StreamModel>>.value(
              <_i5.StreamModel>[],
            ),
          )
          as _i8.Future<List<_i5.StreamModel>>);

  @override
  _i8.Future<List<_i15.CategoryModel>> getCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getCategories, []),
            returnValue: _i8.Future<List<_i15.CategoryModel>>.value(
              <_i15.CategoryModel>[],
            ),
            returnValueForMissingStub:
                _i8.Future<List<_i15.CategoryModel>>.value(
                  <_i15.CategoryModel>[],
                ),
          )
          as _i8.Future<List<_i15.CategoryModel>>);

  @override
  _i8.Future<_i5.StreamModel> followStreamer(String? streamId) =>
      (super.noSuchMethod(
            Invocation.method(#followStreamer, [streamId]),
            returnValue: _i8.Future<_i5.StreamModel>.value(
              _FakeStreamModel_3(
                this,
                Invocation.method(#followStreamer, [streamId]),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i5.StreamModel>.value(
              _FakeStreamModel_3(
                this,
                Invocation.method(#followStreamer, [streamId]),
              ),
            ),
          )
          as _i8.Future<_i5.StreamModel>);
}

/// A class which mocks [StreamRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockStreamRepository extends _i1.Mock implements _i6.StreamRepository {
  @override
  _i8.Future<_i3.Either<_i10.Failure, List<_i16.StreamEntity>>> getStreams({
    String? categoryId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getStreams, [], {#categoryId: categoryId}),
            returnValue:
                _i8.Future<
                  _i3.Either<_i10.Failure, List<_i16.StreamEntity>>
                >.value(
                  _FakeEither_1<_i10.Failure, List<_i16.StreamEntity>>(
                    this,
                    Invocation.method(#getStreams, [], {
                      #categoryId: categoryId,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i8.Future<
                  _i3.Either<_i10.Failure, List<_i16.StreamEntity>>
                >.value(
                  _FakeEither_1<_i10.Failure, List<_i16.StreamEntity>>(
                    this,
                    Invocation.method(#getStreams, [], {
                      #categoryId: categoryId,
                    }),
                  ),
                ),
          )
          as _i8.Future<_i3.Either<_i10.Failure, List<_i16.StreamEntity>>>);

  @override
  _i8.Future<_i3.Either<_i10.Failure, List<_i17.CategoryEntity>>>
  getCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getCategories, []),
            returnValue:
                _i8.Future<
                  _i3.Either<_i10.Failure, List<_i17.CategoryEntity>>
                >.value(
                  _FakeEither_1<_i10.Failure, List<_i17.CategoryEntity>>(
                    this,
                    Invocation.method(#getCategories, []),
                  ),
                ),
            returnValueForMissingStub:
                _i8.Future<
                  _i3.Either<_i10.Failure, List<_i17.CategoryEntity>>
                >.value(
                  _FakeEither_1<_i10.Failure, List<_i17.CategoryEntity>>(
                    this,
                    Invocation.method(#getCategories, []),
                  ),
                ),
          )
          as _i8.Future<_i3.Either<_i10.Failure, List<_i17.CategoryEntity>>>);

  @override
  _i8.Future<_i3.Either<_i10.Failure, _i16.StreamEntity>> followStreamer(
    String? streamId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#followStreamer, [streamId]),
            returnValue:
                _i8.Future<_i3.Either<_i10.Failure, _i16.StreamEntity>>.value(
                  _FakeEither_1<_i10.Failure, _i16.StreamEntity>(
                    this,
                    Invocation.method(#followStreamer, [streamId]),
                  ),
                ),
            returnValueForMissingStub:
                _i8.Future<_i3.Either<_i10.Failure, _i16.StreamEntity>>.value(
                  _FakeEither_1<_i10.Failure, _i16.StreamEntity>(
                    this,
                    Invocation.method(#followStreamer, [streamId]),
                  ),
                ),
          )
          as _i8.Future<_i3.Either<_i10.Failure, _i16.StreamEntity>>);
}

/// A class which mocks [GetStreamsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetStreamsUseCase extends _i1.Mock implements _i18.GetStreamsUseCase {
  @override
  _i6.StreamRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeStreamRepository_4(
              this,
              Invocation.getter(#repository),
            ),
            returnValueForMissingStub: _FakeStreamRepository_4(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i6.StreamRepository);

  @override
  _i8.Future<_i3.Either<_i10.Failure, List<_i16.StreamEntity>>> call({
    String? categoryId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#categoryId: categoryId}),
            returnValue:
                _i8.Future<
                  _i3.Either<_i10.Failure, List<_i16.StreamEntity>>
                >.value(
                  _FakeEither_1<_i10.Failure, List<_i16.StreamEntity>>(
                    this,
                    Invocation.method(#call, [], {#categoryId: categoryId}),
                  ),
                ),
            returnValueForMissingStub:
                _i8.Future<
                  _i3.Either<_i10.Failure, List<_i16.StreamEntity>>
                >.value(
                  _FakeEither_1<_i10.Failure, List<_i16.StreamEntity>>(
                    this,
                    Invocation.method(#call, [], {#categoryId: categoryId}),
                  ),
                ),
          )
          as _i8.Future<_i3.Either<_i10.Failure, List<_i16.StreamEntity>>>);
}

/// A class which mocks [GetCategoriesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCategoriesUseCase extends _i1.Mock
    implements _i19.GetCategoriesUseCase {
  @override
  _i6.StreamRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeStreamRepository_4(
              this,
              Invocation.getter(#repository),
            ),
            returnValueForMissingStub: _FakeStreamRepository_4(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i6.StreamRepository);

  @override
  _i8.Future<_i3.Either<_i10.Failure, List<_i17.CategoryEntity>>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i8.Future<
                  _i3.Either<_i10.Failure, List<_i17.CategoryEntity>>
                >.value(
                  _FakeEither_1<_i10.Failure, List<_i17.CategoryEntity>>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
            returnValueForMissingStub:
                _i8.Future<
                  _i3.Either<_i10.Failure, List<_i17.CategoryEntity>>
                >.value(
                  _FakeEither_1<_i10.Failure, List<_i17.CategoryEntity>>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i8.Future<_i3.Either<_i10.Failure, List<_i17.CategoryEntity>>>);
}

/// A class which mocks [FollowStreamerUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockFollowStreamerUseCase extends _i1.Mock
    implements _i20.FollowStreamerUseCase {
  @override
  _i6.StreamRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeStreamRepository_4(
              this,
              Invocation.getter(#repository),
            ),
            returnValueForMissingStub: _FakeStreamRepository_4(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i6.StreamRepository);

  @override
  _i8.Future<_i3.Either<_i10.Failure, _i16.StreamEntity>> call(
    String? streamId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [streamId]),
            returnValue:
                _i8.Future<_i3.Either<_i10.Failure, _i16.StreamEntity>>.value(
                  _FakeEither_1<_i10.Failure, _i16.StreamEntity>(
                    this,
                    Invocation.method(#call, [streamId]),
                  ),
                ),
            returnValueForMissingStub:
                _i8.Future<_i3.Either<_i10.Failure, _i16.StreamEntity>>.value(
                  _FakeEither_1<_i10.Failure, _i16.StreamEntity>(
                    this,
                    Invocation.method(#call, [streamId]),
                  ),
                ),
          )
          as _i8.Future<_i3.Either<_i10.Failure, _i16.StreamEntity>>);
}
